var t=readline();
    while(t--)
    {
        n=readline();
        l=0,r=0,u=0,d=0;
        for(var i=0;i<n;++i)
        {
            x=readline();
            y=readline();
            if(x<0)
            {
                l=1;
            }
            if(x>0)
            {                
                r=1;
            }
            if(y<0)
            {
                d=1;
            }
            if(y>0)
            {
                u=1;
            }
        }
        if((l+r+u+d)==4)
        {
            print("NO");
        }
        else
        {
            print("YES");
        }
    }